title: Stormed Out
description: The official website for Stormed Out
theme: just-the-docs

url: https://Stormed-Out.github.io/SO

search_enabled: true

search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
  focus_shortcut_key: 'k'

nav_enabled: true

markup / liquid-based content.
footer_content: "Copyright &copy; 2024 Patrick Marjamjelly. 

last_edit_timestamp: true 
last_edit_time_format: "%b %e %Y at %I:%M %p"

color_scheme: dark

aux_links:
  Github: https://github.com/Stormed-Out/SO
